export const INCREMENT_GAMES= "INCREMENT_GAMES";
export const DECREMENT_GAMES= "DECREMENT_GAMES";
export const INCREMENT_BOOKS= "INCREMENT_BOOKS";
export const DECREMENT_BOOKS= "DECREMENT_BOOKS";
export const INCREMENT_COURSES= "INCREMENT_COURSES";
export const DECREMENT_COURSES= "DECREMENT_COURSES";
